### ISSUE TITLE
Use context managers

### ISSUE THREAD

**Issue by 2Cubed** [CactusBot/CactusBot#256]
We should be using context managers in a number of places which we currently aren't. (For example, [`WebSocket`](http://aiohttp.readthedocs.io/en/stable/client.html#websockets)!)

In addition to making the code cleaner and more Pythonic, it will help with #62.

**Comment by 2Cubed** [comment]
Our *tests* output the following:

```python
Exception ignored in: <bound method ClientSession.__del__ of <cactusbot.api.CactusAPI object at 0x7f2afea59e10>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 96, in __del__
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 437, in close
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 239, in close
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/helpers.py", line 90, in create_future
  File "/usr/lib/python3.5/asyncio/base_events.py", line 252, in create_future
AttributeError: 'NoneType' object has no attribute 'Future'
Exception ignored in: <bound method ClientSession.__del__ of <cactusbot.api.CactusAPI object at 0x7f2b01020710>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 96, in __del__
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 437, in close
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 239, in close
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method ClientSession.__del__ of <cactusbot.api.CactusAPI object at 0x7f2afea6f1d0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 96, in __del__
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 437, in close
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 239, in close
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method ClientSession.__del__ of <cactusbot.api.CactusAPI object at 0x7f2afea6ff60>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 96, in __del__
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 437, in close
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 239, in close
TypeError: 'NoneType' object is not callable
```

**Comment by 2Cubed** [comment]
`WebSocket` was already using context managers, through `aiohttp.ClientSession` (were not overridden).

**Comment by 2Cubed** [comment]
Context managers were implemented on `fix/clean-shutdown`. Improved our code's "Pythonic-ness" and overall cleanliness, but did not entirely solve #62.
